### ISSUE TITLE
Update README.md to show list of contributors

### ISSUE THREAD

**Issue by codemarka** [codemarka/codemarka-client#1]

**Comment by github4maninder** [comment]
Hi, I would like to work on this request

**Comment by github4maninder** [comment]
![Screen Shot 2022-01-07 at 9 40 14 AM](https://user-images.githubusercontent.com/90073393/148559832-7e153cfc-7184-4ac5-b7c0-e87b82c3e995.JPG)


let me know if its okay to insert contributors info at the bottom of the readme or should I include is on the top

**Comment by github4maninder** [comment]
this issue is resolved. kindly close this issue
